# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BulldozerDtmProvider
                                 A QGIS plugin
 BulldozerDtmProvider
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-17
        copyright            : (C) 2023 by CNES
        email                : alexia.mondot@cnes.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'CNES'
__date__ = '2023-04-17'
__copyright__ = '(C) 2023 by CNES'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BulldozerDtmProvider class from file BulldozerDtmProvider.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BulldozerDtmProvider import BulldozerDtmProviderPlugin
    return BulldozerDtmProviderPlugin()
